spring:
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://39.100.203.174:3316/kuaishou?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
      username: root
      password: xijia@203.174
  redis:
    host: 124.223.52.171
    port: 15820
    password: zhao15800
    # 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      pool:
        max-active: 500
        max-wait: 500
        max-idle: 500
        min-idle: 0
  ftp:
    host: 124.223.52.171
    port: 15822
    username: root
    password: zhao15800
    dest-path: a/a

logging:
  config: classpath:log4j2/log4j2-dev.yml
